/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : string } |
  { 'err' : string };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type UserId = bigint;
export interface _SERVICE {
  'addSongToPlaylist' : ActorMethod<[string, bigint, string], Result>,
  'createPlaylist' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deletePlaylist' : ActorMethod<[string, bigint], Result>,
  'getLikedSongs' : ActorMethod<
    [string],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'getMe' : ActorMethod<
    [string],
    [] | [{ 'id' : UserId, 'username' : string, 'email' : string }]
  >,
  'getPlaylists' : ActorMethod<
    [string],
    {
        'ok' : Array<
          { 'id' : bigint, 'name' : string, 'videoIds' : Array<string> }
        >
      } |
      { 'err' : string }
  >,
  'likeSong' : ActorMethod<[string, string], Result>,
  'login' : ActorMethod<[string, string], AuthResult>,
  'logout' : ActorMethod<[string], Result>,
  'register' : ActorMethod<[string, string], AuthResult>,
  'removeSongFromPlaylist' : ActorMethod<[string, bigint, string], Result>,
  'unlikeSong' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];