/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserId = IDL.Nat;
export const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addSongToPlaylist' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
  'createPlaylist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'deletePlaylist' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  'getLikedSongs' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMe' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'id' : UserId,
            'username' : IDL.Text,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getPlaylists' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'name' : IDL.Text,
              'videoIds' : IDL.Vec(IDL.Text),
            })
          ),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'likeSong' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'logout' : IDL.Func([IDL.Text], [Result], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'removeSongFromPlaylist' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'unlikeSong' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserId = IDL.Nat;
  const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    'addSongToPlaylist' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
    'createPlaylist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'deletePlaylist' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
    'getLikedSongs' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMe' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'id' : UserId,
              'username' : IDL.Text,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getPlaylists' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(
              IDL.Record({
                'id' : IDL.Nat,
                'name' : IDL.Text,
                'videoIds' : IDL.Vec(IDL.Text),
              })
            ),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'likeSong' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'logout' : IDL.Func([IDL.Text], [Result], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'removeSongFromPlaylist' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'unlikeSong' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };